services: 
  api-gateway:
    build: ../microservices/api-gateway
    ports:
      - "8080:8000"
    networks:
      - microservices-net
    environment:
      - CONSUL_HOST=consul
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - consul
      - rabbitmq
  query:
    build: ../microservices/query
    ports:
      - "8001:8000"
    networks:
      - microservices-net
    environment:
      - CONSUL_HOST=consul
      - RABBITMQ_HOST=rabbitmq
      - PORT=8000
      - DATABASE_URL=postgresql://admin:admin@postgres-query:5432/query
    depends_on:
      - consul
      - rabbitmq
      - postgres-query
  postgres-query:
    image: postgres:15
    environment:
      POSTGRES_DB: query
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_query:/var/lib/postgresql/data
    networks:
      - microservices-net
  collector:
    build: ../microservices/collector
    ports:
      - "8002:8000"
    networks:
      - microservices-net
    environment:
      - CONSUL_HOST=consul
      - RABBITMQ_HOST=rabbitmq
      - PORT=8000
      - DATABASE_URL=postgresql://admin:admin@postgres-trends:5432/trends
      - PROXY=http://JfNMSNSKm-session-raSCc3:vMBZwiPmY5EdXZc5@proxy.proxy302.com:2222
    depends_on:
      - consul
      - rabbitmq
      - postgres-trends
  postgres-trends:
    image: postgres:15
    environment:
      POSTGRES_DB: trends
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_trends:/var/lib/postgresql/data
    networks:
      - microservices-net
  user-management:
    build: ../microservices/user_management
    ports:
      - "8003:8000"
    networks:
      - microservices-net
    environment:
      - CONSUL_HOST=consul
      - PORT=8000
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - consul
      - rabbitmq

  permission:
    build: ../microservices/permission
    ports:
      - "8004:8000"
    networks:
      - microservices-net
    environment:
      - CONSUL_HOST=consul
      - PORT=8000
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - user-management
      - consul
      - rabbitmq

  # 新增基础设施服务
  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    networks:
      - microservices-net
    command: agent -server -ui -node=consul-server -bootstrap-expect=1 -client=0.0.0.0

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices-net
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
volumes:
  postgres_data_query:
  postgres_data_trends:

networks:
  microservices-net:
    driver: bridge

